runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: _site/index.html
  upload: _site/index.html

- url: /(.*\/)
  static_files: _site/\1index.html
  upload: _site/.*/index.html

- url: /
  static_dir: _site/
